"""
Prescription models for the Medilink platform.

This module provides prescription management with:
- Doctor-issued prescriptions linked to appointments
- PDF file storage (generated by frontend)
- Patient and clinic associations
- Full prescription history tracking
- Medication items with dosage instructions
"""
import uuid
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.core.validators import FileExtensionValidator

from accounts.models import User
from providers.models.provider import Provider


def prescription_pdf_path(instance, filename):
    """Generate upload path for prescription PDFs."""
    return f'prescriptions/{instance.patient.id}/{instance.id}/{filename}'


class PrescriptionStatus(models.TextChoices):
    """Prescription status choices."""
    DRAFT = 'DRAFT', 'Draft'
    ISSUED = 'ISSUED', 'Issued'
    DISPENSED = 'DISPENSED', 'Dispensed'
    EXPIRED = 'EXPIRED', 'Expired'
    CANCELLED = 'CANCELLED', 'Cancelled'


class Prescription(models.Model):
    """
    Prescription model for doctors to issue prescriptions to patients.
    
    Each prescription is linked to:
    - A doctor (required)
    - A patient (required - can be User or PatientRecord)
    - An appointment (required - must be completed)
    - A clinic (optional)
    
    The PDF file is generated by the frontend and uploaded.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    
    # Reference number for easy identification
    reference_number = models.CharField(
        max_length=50,
        unique=True,
        editable=False,
        help_text='Unique prescription reference number'
    )
    
    # Doctor who issued the prescription (required)
    doctor = models.ForeignKey(
        'providers.Doctor',
        on_delete=models.PROTECT,
        related_name='prescriptions',
        help_text='Doctor who issued this prescription'
    )
    
    # Patient identification (one of these must be set)
    patient = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='prescriptions',
        help_text='Patient with a user account'
    )
    patient_record = models.ForeignKey(
        'patients.PatientRecord',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='prescriptions',
        help_text='Patient record (for patients without accounts)'
    )
    
    # Clinic (optional)
    clinic = models.ForeignKey(
        'providers.Clinic',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='prescriptions',
        help_text='Clinic where prescription was issued'
    )
    
    # Appointment link (required - only for completed appointments)
    appointment = models.OneToOneField(
        'appointments.Appointment',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='prescription',
        help_text='Associated appointment'
    )
    
    # Medical content
    diagnosis = models.TextField(
        blank=True,
        help_text='Diagnosis or reason for prescription'
    )
    notes = models.TextField(
        blank=True,
        help_text='Additional notes for the prescription'
    )
    instructions = models.TextField(
        blank=True,
        help_text='General instructions for the patient'
    )
    
    # PDF file (generated and uploaded by frontend)
    pdf_file = models.FileField(
        upload_to=prescription_pdf_path,
        null=True,
        blank=True,
        validators=[FileExtensionValidator(['pdf'])],
        help_text='PDF file of the prescription'
    )
    
    # Status
    status = models.CharField(
        max_length=20,
        choices=PrescriptionStatus.choices,
        default=PrescriptionStatus.DRAFT,
        db_index=True,
        help_text='Current status of the prescription'
    )
    
    # Validity period
    valid_until = models.DateField(
        null=True,
        blank=True,
        help_text='Date until which the prescription is valid'
    )
    
    # Timestamps
    issued_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the prescription was issued'
    )
    created_at = models.DateTimeField(
        default=timezone.now,
        help_text='When the prescription was created'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text='Last update timestamp'
    )
    
    class Meta:
        db_table = 'prescription_documents'
        verbose_name = 'Prescription'
        verbose_name_plural = 'Prescriptions'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['doctor', 'created_at']),
            models.Index(fields=['patient', 'created_at']),
            models.Index(fields=['patient_record', 'created_at']),
            models.Index(fields=['clinic', 'created_at']),
            models.Index(fields=['status']),
            models.Index(fields=['reference_number']),
        ]
        constraints = [
            # Ensure at least one patient identifier is provided
            models.CheckConstraint(
                condition=(
                    models.Q(patient__isnull=False) |
                    models.Q(patient_record__isnull=False)
                ),
                name='prescription_has_patient'
            ),
            # Ensure not both patient types are set
            models.CheckConstraint(
                condition=~(
                    models.Q(patient__isnull=False) &
                    models.Q(patient_record__isnull=False)
                ),
                name='prescription_single_patient_type'
            ),
        ]
    
    def __str__(self):
        patient_name = self.get_patient_display_name()
        return f'Prescription {self.reference_number} - {patient_name}'
    
    def save(self, *args, **kwargs):
        """Generate reference number if not set."""
        if not self.reference_number:
            self.reference_number = self._generate_reference_number()
        super().save(*args, **kwargs)
    
    def _generate_reference_number(self):
        """Generate a unique reference number."""
        import random
        import string
        from datetime import date
        
        today = date.today()
        prefix = f'RX{today.strftime("%y%m%d")}'
        suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        return f'{prefix}-{suffix}'
    
    def clean(self):
        """Validate the prescription."""
        super().clean()
        
        # Validate patient identification
        if not self.patient and not self.patient_record:
            raise ValidationError(
                'Either patient or patient_record must be provided.'
            )
        
        if self.patient and self.patient_record:
            raise ValidationError(
                'Cannot have both patient and patient_record.'
            )
        
        # Validate appointment status (must be confirmed or completed)
        if self.appointment:
            from appointments.models import AppointmentStatus
            valid_statuses = [AppointmentStatus.CONFIRMED, AppointmentStatus.COMPLETED]
            if self.appointment.status not in valid_statuses:
                raise ValidationError({
                    'appointment': 'Prescription can only be issued for confirmed or completed appointments.'
                })
    
    def get_patient_display_name(self):
        """Get display name for the patient using centralized utility."""
        from common.utils import get_patient_display_name
        return get_patient_display_name(self.patient, self.patient_record)
    
    def issue(self, save=True):
        """Issue the prescription (change from draft to issued)."""
        if self.status != PrescriptionStatus.DRAFT:
            raise ValidationError(f'Cannot issue prescription with status {self.status}')
        
        self.status = PrescriptionStatus.ISSUED
        self.issued_at = timezone.now()
        
        if save:
            self.save(update_fields=['status', 'issued_at', 'updated_at'])
    
    def mark_dispensed(self, save=True):
        """Mark the prescription as dispensed."""
        if self.status != PrescriptionStatus.ISSUED:
            raise ValidationError(f'Cannot mark as dispensed with status {self.status}')
        
        self.status = PrescriptionStatus.DISPENSED
        
        if save:
            self.save(update_fields=['status', 'updated_at'])
    
    def cancel(self, save=True):
        """Cancel the prescription."""
        if self.status in [PrescriptionStatus.DISPENSED, PrescriptionStatus.CANCELLED]:
            raise ValidationError(f'Cannot cancel prescription with status {self.status}')
        
        self.status = PrescriptionStatus.CANCELLED
        
        if save:
            self.save(update_fields=['status', 'updated_at'])
    
    @property
    def is_valid(self):
        """Check if prescription is still valid."""
        if self.status != PrescriptionStatus.ISSUED:
            return False
        if self.valid_until and self.valid_until < timezone.now().date():
            return False
        return True


class MedicationType(models.TextChoices):
    """Types of medications."""
    TABLET = 'TABLET', 'Tablet'
    CAPSULE = 'CAPSULE', 'Capsule'
    SYRUP = 'SYRUP', 'Syrup'
    INJECTION = 'INJECTION', 'Injection'
    CREAM = 'CREAM', 'Cream'
    OINTMENT = 'OINTMENT', 'Ointment'
    DROPS = 'DROPS', 'Drops'
    INHALER = 'INHALER', 'Inhaler'
    PATCH = 'PATCH', 'Patch'
    SUPPOSITORY = 'SUPPOSITORY', 'Suppository'
    OTHER = 'OTHER', 'Other'


class DosageFrequency(models.TextChoices):
    """Common dosage frequencies."""
    ONCE_DAILY = 'QD', 'Once daily'
    TWICE_DAILY = 'BID', 'Twice daily'
    THREE_TIMES_DAILY = 'TID', 'Three times daily'
    FOUR_TIMES_DAILY = 'QID', 'Four times daily'
    EVERY_MORNING = 'QAM', 'Every morning'
    EVERY_EVENING = 'QPM', 'Every evening'
    EVERY_BEDTIME = 'QHS', 'At bedtime'
    AS_NEEDED = 'PRN', 'As needed'
    EVERY_4_HOURS = 'Q4H', 'Every 4 hours'
    EVERY_6_HOURS = 'Q6H', 'Every 6 hours'
    EVERY_8_HOURS = 'Q8H', 'Every 8 hours'
    EVERY_12_HOURS = 'Q12H', 'Every 12 hours'
    ONCE_WEEKLY = 'QW', 'Once weekly'
    CUSTOM = 'CUSTOM', 'Custom schedule'


class PrescriptionItem(models.Model):
    """
    Individual medication item within a prescription.
    
    Contains details about each medication prescribed:
    - Medication name and type
    - Dosage information
    - Duration
    - Special instructions
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    
    prescription = models.ForeignKey(
        Prescription,
        on_delete=models.CASCADE,
        related_name='items',
        help_text='Parent prescription'
    )
    
    # Medication details
    medication_name = models.CharField(
        max_length=255,
        help_text='Name of the medication'
    )
    medication_type = models.CharField(
        max_length=20,
        choices=MedicationType.choices,
        default=MedicationType.TABLET,
        help_text='Type of medication'
    )
    generic_name = models.CharField(
        max_length=255,
        blank=True,
        help_text='Generic name of the medication'
    )
    strength = models.CharField(
        max_length=100,
        blank=True,
        help_text='Strength/concentration (e.g., 500mg, 5ml)'
    )
    
    # Dosage instructions
    dosage = models.CharField(
        max_length=100,
        help_text='Dosage amount (e.g., 1 tablet, 2 capsules, 5ml)'
    )
    frequency = models.CharField(
        max_length=20,
        choices=DosageFrequency.choices,
        default=DosageFrequency.ONCE_DAILY,
        help_text='How often to take the medication'
    )
    custom_frequency = models.CharField(
        max_length=200,
        blank=True,
        help_text='Custom frequency if not in standard list'
    )
    
    # Duration
    duration_days = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text='Duration in days'
    )
    duration_text = models.CharField(
        max_length=100,
        blank=True,
        help_text='Human-readable duration (e.g., "2 weeks", "until finished")'
    )
    
    # Quantity
    quantity = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text='Total quantity to dispense'
    )
    quantity_unit = models.CharField(
        max_length=50,
        blank=True,
        help_text='Unit for quantity (tablets, ml, etc.)'
    )
    
    # Additional instructions
    instructions = models.TextField(
        blank=True,
        help_text='Additional instructions (take with food, avoid alcohol, etc.)'
    )
    
    # Ordering
    order = models.PositiveIntegerField(
        default=0,
        help_text='Order of medication in prescription'
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'prescription_items'
        verbose_name = 'Prescription Item'
        verbose_name_plural = 'Prescription Items'
        ordering = ['order', 'created_at']
    
    def __str__(self):
        return f'{self.medication_name} - {self.dosage} {self.get_frequency_display()}'
    
    def get_full_instructions(self):
        """Get complete dosage instructions as a string."""
        freq = self.custom_frequency if self.frequency == DosageFrequency.CUSTOM else self.get_frequency_display()
        instructions = f'{self.dosage} {freq}'
        
        if self.duration_text:
            instructions += f' for {self.duration_text}'
        elif self.duration_days:
            instructions += f' for {self.duration_days} days'
        
        if self.instructions:
            instructions += f'. {self.instructions}'
        
        return instructions
